name: Update Forked Repository
on:
  push:
    branches:
      - main
jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Fetch Upstream Changes
        run: git fetch upstream
      - name: Merge Upstream Changes
        run: git merge upstream/main
      - name: Push Changes to Forked Repository
        run: git push origin main
